home commited
soumyayattinahalli928/online_meeting_schrduling pull request #1
Opened 2024-04-24 10:42 UTC by aishwarya0608

,  project (online_meeting_scheduling)  ,

2024-04-24 10:57 UTC, robinrgc requested changes
make application name changes

2024-04-24 14:15 UTC, aishwarya0608 commented
Changes Done

2024-04-24 17:21 UTC, robinrgc approved these changes

2024-04-25 09:12 UTC, robinrgc approved these changes

2024-04-25 09:12 UTC, merged